name: Build release files
on:
  workflow_dispatch:
  #push:
  #  branches: [ main ]
  #  paths:
  #    - 'src/ontology/imports/**_import.owl'
  #    - 'src/ontology/midas-data-edit.owl'

jobs:
  build:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.4
    strategy:
      max-parallel: 1
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: work around permission issue
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        
      - name: Update release files
        run: cd src/ontology/ && make ROBOT_ENV='ROBOT_JAVA_ARGS=-Xmx6G' GITHUB_ACTION=true prepare_release
      
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: matentzn
          author_email: nicolas.matentzoglu@gmail.com
          message: 'Update release files'
          add: '*.owl'
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
